global:
  scrape_interval: "20s"
scrape_configs:
  - job_name: "nodejs-app"
    static_configs:
      - targets:
          - node-app:3000 # Because in docker the container can recognize other container with their names
          # - localhost:3000
